//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("16.1.3.1")]
[assembly: AssemblyVersion("16.1.3.1")]
[assembly: AssemblyInformationalVersion("16.1.3+7394b0f")]
