//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("16.1.11.0")]
[assembly: AssemblyVersion("16.1.11.0")]
[assembly: AssemblyInformationalVersion("16.1.11+ad01a9d")]
