//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("16.0.4.148")]
[assembly: AssemblyVersion("16.0.4.148")]
[assembly: AssemblyInformationalVersion("16.0.4-net-script-to-build-open-source-including-compiled-schemas.1+6945a17")]
